### PR TITLE
Refactor iterator

### PR DESCRIPTION
**Pull request by panicbit**
It seems like the "!first_run" branch was dead,
because the "first_run" branch set the variable to "true" again.
It was never set to false.
That does not look like it was intentional,
but the tests were passing, so I'm gonna assume it's fine
and refactored the hell out of that deeply nested bit of code :smiley:

---
This change is [Reviewable](https://reviewable.io/reviews/0xpr03/linebuffer/2)

### CODE REVIEW

**Comment by 0xpr03** [comment]
Oh that sounds bad. Gotta investigate this and test what exactly went on. Thanks for finding this already!

**Comment by 0xpr03** [comment]
Logically we can avoid the check after doing it initially, so I'd re-add the first_run flag but actually switch it this time.

**Comment by panicbit** [comment]
Can you add a failing testcase for this before I attempt to change the logic, please?

**Comment by 0xpr03** [comment]
I wanted to send you the re-added flag and ask for checking of logic failures but I'll come up with some tests by myself ;)

**Pull request merged**
